/**
 * Quality Assurance Plan picker lists — taken from the values SPDC uses in
 * Quality Assurance Plan Week 50.xlsx. Used by the portal row editors and as
 * Excel drop-downs in the QAP export (free text is still allowed in both).
 */
export const QAP_PICKERS = {
  section: [
    "Site Survey",
    "Excavation",
    "Anti Termite Treatment",
    "Back Filling",
    "Plain Cement Concrete",
    "Mix Design",
    "Reinforcement",
    "Formwork",
    "Concreting",
    "Structural Steel",
    "Grouting of Insert Plate and Anchor Bolt",
    "Masonry Work - Brick/ Concrete Block",
    "Plastering",
    "Water Proofing",
    "Flooring",
    "Wall tile work-Dado fixing",
    "Painting",
    "Granular Sub Base",
    "Wet Mix Macadam",
    "Paver Block Laying",
    "RCC hume pipe laying",
  ],
  frequency: [
    "Each structure",
    "Each structure & Element",
    "Each layer",
    "Each lot",
    "Every lot",
    "Once in every lot",
    "Once in every source",
    "Once Initial Start",
    "Every Consignment",
    "Every foundation and trench",
    "Each trench",
    "Each Joint",
    "Brand source change",
    "Every 200 cum",
    "1 test / 500 sqm",
    "Every layout",
    "Daily",
    "Weekly",
    "As per concreting item",
  ],
  codeOfConformance: [
    "Approved Drawing",
    "Approved Drawing & BBS",
    "Client Reference",
    "Client Reference/ Approved Drawing",
    "Manufacturer Technical Data Sheet",
    "Morth Specification",
    "IS 456",
    "IS456: 2000 , IS:10262 :2009",
    "IS:10262 :2009",
    "IS 3025, IS 456",
    "IS-383",
    "IS-2386 , IS 383",
    "IS-1786",
    "IS 6313",
    "IS 15658",
  ],
  testAgency: [
    "Site Lab",
    "Approved external lab",
    "Site Lab/Approved external lab",
    "Manufacturer",
    "Manufacturer / Approved external lab",
    "Manufacturer Test Certificate",
    "Approved external agency",
  ],
  contractorPerformer: ["Site Engr", "QA/QC Engr", "QC Engr", "Surveyor", "Foreman", "Contractor"],
  contractorChecker: ["QC Engr", "QA/QC Engr", "Site Engr", "Project Manager"],
  pmcRole: ["Witness", "Review", "Approve", "Random", "Hold Point"],
  clientRole: ["Random", "Witness", "Review", "Approve"],
  records: [
    "Work Check List",
    "TPC",
    "MTC",
    "TPC & MTC",
    "Test Report",
    "Material Data Sheet",
    "MTC/Technical Data Sheet",
    "Register/Note",
    "Calibration Certificate",
    "Setting out plan",
    "Level book",
    "Bar Bending Schedule",
    "Concrete log",
    "Pour card",
  ],
  remarks: ["Pending", "In Progress", "Completed", "Not Applicable"],
  daily: ["Yes", "No", "-"],
} as const;

export type QapPickerKey = keyof typeof QAP_PICKERS;

/** Legend abbreviations printed on the QAP sheet. */
export const QAP_LEGENDS: readonly [string, string][] = [
  ["BBS", "Bar Bending Schedule"],
  ["MTC", "Material Test Certificate"],
  ["RCC", "Reinforced Cement Concrete"],
  ["CUM", "Cubic Meter"],
  ["PCC", "Plain Cement Concrete"],
  ["SQM", "Square Meter"],
  ["HSE", "Health Safety & Environment"],
  ["QA", "Quality Assurance"],
  ["TBM", "Temporary Bench Mark"],
  ["IS", "Indian Standard"],
  ["QC", "Quality Control"],
  ["TPC", "Third Party Confirmation"],
];
